package cn.jbolt.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDevicestorage<M extends BaseDevicestorage<M>> extends Model<M> implements IBean {

	public M setDeviceId(java.lang.Integer deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceId() {
		return getInt("device_id");
	}

	public M setDeviceName(java.lang.String deviceName) {
		set("device_name", deviceName);
		return (M)this;
	}
	
	public java.lang.String getDeviceName() {
		return getStr("device_name");
	}

	public M setDeviceBrand(java.lang.String deviceBrand) {
		set("device_brand", deviceBrand);
		return (M)this;
	}
	
	public java.lang.String getDeviceBrand() {
		return getStr("device_brand");
	}

	public M setDeviceModel(java.lang.String deviceModel) {
		set("device_model", deviceModel);
		return (M)this;
	}
	
	public java.lang.String getDeviceModel() {
		return getStr("device_model");
	}

	public M setDeviceNumber(java.lang.Integer deviceNumber) {
		set("device_number", deviceNumber);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceNumber() {
		return getInt("device_number");
	}

	public M setDeviceLocation(java.lang.String deviceLocation) {
		set("device_location", deviceLocation);
		return (M)this;
	}
	
	public java.lang.String getDeviceLocation() {
		return getStr("device_location");
	}

	public M setDeviceDate(java.util.Date deviceDate) {
		set("device_date", deviceDate);
		return (M)this;
	}
	
	public java.util.Date getDeviceDate() {
		return get("device_date");
	}

	public M setDeviceNote(java.lang.String deviceNote) {
		set("device_note", deviceNote);
		return (M)this;
	}
	
	public java.lang.String getDeviceNote() {
		return getStr("device_note");
	}

}
