package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseDevicestorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devicestorage extends BaseDevicestorage<Devicestorage> {
	public static final Devicestorage dao = new Devicestorage().dao();
}
