package cn.jbolt.common.model;

import cn.jbolt.common.model.base.BaseTuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tuser extends BaseTuser<Tuser> {
	public static final Tuser dao = new Tuser().dao();
}
